{
 "title": "Loki Kubernetes Logs",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "loki" },
   { "name": "query", "label": "Search Query word" },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   },
   {
    "name": "stream",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Log Distribution View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ds" },
  {
   "title": "Total logs by time / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({stream=~\"$stream\", namespace=~\"$namespace\", stream=~\"$stream\", app=~\"$app\", container=~\"$container\"} |~ `(?i)$query` [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  {
   "title": "Total log by stream / $__interval",
   "type": "timeseries",
   "description": "Stream percentile",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(stream) (count_over_time({stream=~\"$stream\",app=~\"$app\", namespace=~\"$namespace\", container=~\"$container\"} |~ \"(?i)$query\" [$__interval]))"
    }
   ]
  },
  {
   "title": "total log line by app / $__interval",
   "type": "timeseries",
   "description": "根据app分组统计日志量大小",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"$app\", container=~\"$container\", namespace=~\"$namespace\", stream=~\"$stream\"} |~ \"(?i)$query\" [$__interval])) by (app)"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Log Content",
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", stream=~\"$stream\", app =~\"$app\", container=~\"$container\"} |~ \"(?i)$query\""
    }
   ]
  }
 ]
}