{
 "title": "k8s cluster test",
 "description": "monitor for k8s cluster include node and pod",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status Overall (all)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(kube_node_status_condition{condition=\"Ready\", status=\"true\"}, \"node_r\", \"$1\", \"node\", \"cn-shenzhen.(.*)\")",
     "legendFormat": "{{node_r}}"
    }
   ]
  },
  {
   "title": "Nodes ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Namespaces ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Total pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_service_created{namespace=\"default\",service=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "Cluster Node Overall (all)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overall CPU usage in cluster ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) /sum(irate(node_cpu_seconds_total[1m])) * 100",
       "legendFormat": "Total Used CPU in cluster"
      }
     ]
    },
    {
     "title": "Node CPU usage in cluster ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[$interval])) by (node) / sum(irate(node_cpu_seconds_total[$interval])) by (node) * 100",
       "legendFormat": "{{node}} "
      }
     ]
    },
    {
     "title": "Node  wise load in cluster (load5)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load5 + on(instance) group_left(node) \nnode_uname_info",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Disk usage in cluster by node(vda)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - node_filesystem_avail_bytes{device=~\"^/dev/vda.*\"} / node_filesystem_size_bytes{device=~\"^/dev/.*\"}) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Overall memory usage in cluster",
     "type": "timeseries",
     "description": "This panel shows node memory usage:\n\nnode_memory_MemTotal - node_memory_MemAvailable",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/sum(node_memory_MemTotal_bytes) * 100",
       "legendFormat": "Total memory used"
      }
     ]
    },
    {
     "title": "Memory usage in cluster by node",
     "type": "timeseries",
     "description": "This panel shows node memory usage:\n\nnode_memory_MemTotal - node_memory_MemAvailable",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes * 100) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory usage by namespace in cluster",
     "type": "timeseries",
     "description": "This panel shows node memory usage:\n\ncontainer working set",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (namespace)(container_memory_working_set_bytes{pod!=\"POD\",namespace!=\"\"}))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Overall ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu  ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{node=~\"^$node$\"}[$interval])) by (mode) / scalar(count(count(node_cpu_seconds_total{node=~\"^$node$\"}) by (cpu))) *100",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{node=~\"^$node$\"}",
       "legendFormat": "load.1m"
      },
      {
       "expr": "node_load5{node=~\"^$node$\"}",
       "legendFormat": "load.5m"
      },
      {
       "expr": "node_load15{node=~\"^$node$\"}",
       "legendFormat": "load.15m"
      }
     ]
    },
    {
     "title": "Read/Write bytes/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{node=~\"^$node$\",device=\"vda\"}[$interval])",
       "legendFormat": "read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{node=~\"^$node$\",device=\"vda\"}[$interval])",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Read/Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{node=~\"^$node$\",device=\"vda\"}[2m])",
       "legendFormat": "read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{node=~\"^$node$\",device=\"vda\"}[2m])",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Mem",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"^$node$\"}",
       "legendFormat": "total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"^$node$\"} - node_memory_MemFree_bytes{node=~\"^$node$\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"^$node$\"} - node_memory_MemAvailable_bytes{node=~\"^$node$\"}",
       "legendFormat": "actualused"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{node=~\"^$node$\"}",
       "legendFormat": "available"
      }
     ]
    },
    {
     "title": "Net bps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{node=~\"^$node$\",device=\"eth0\"}[$interval])*8",
       "legendFormat": "receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{node=~\"^$node$\",device=\"eth0\"}[$interval])*8",
       "legendFormat": "transmit"
      }
     ]
    },
    {
     "title": "Net pps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{node=~\"^$node$\",device=\"eth0\"}[$interval])",
       "legendFormat": "receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{node=~\"^$node$\",device=\"eth0\"}[$interval])",
       "legendFormat": "transmit"
      },
      {
       "expr": "irate(node_network_receive_errs_total{node=~\"^$node$\",device=\"eth0\"}[$interval])",
       "legendFormat": "receive_errs"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{node=~\"^$node$\",device=\"eth0\"}[$interval])",
       "legendFormat": "transmit_errs"
      }
     ]
    },
    {
     "title": "Net tcp",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_inuse{node=~\"^$node$\"}",
       "legendFormat": "listen"
      },
      {
       "expr": "node_sockstat_TCP_alloc{node=~\"^$node$\"}",
       "legendFormat": "alloc"
      },
      {
       "expr": "node_sockstat_TCP_tw{node=~\"^$node$\"}",
       "legendFormat": "time_wait"
      },
      {
       "expr": "node_netstat_Tcp_CurrEstab{node=~\"^$node$\"}",
       "legendFormat": "estab"
      },
      {
       "expr": "node_sockstat_sockets_used{node=~\"^$node$\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Available Resource ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster CPU usage ($interval avg)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}[$interval])) / sum (kube_node_status_allocatable{resource=\"cpu\",node=~\"^$node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster memory usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) / sum (kube_node_status_allocatable{resource=\"memory\", node=~\"^$node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster filesystem usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/vda.$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/vda.$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_node_status_allocatable{resource=\"cpu\",node=~\"^$node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_node_status_allocatable{resource=\"memory\", node=~\"^$node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/vda.$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/vda.$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"})"
      }
     ]
    },
    {
     "title": "Panel Title $interval",
     "type": "table",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"^$node$\"}) by (node)",
       "legendFormat": "require_cpu"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\"^$node$\"}) by (node)",
       "legendFormat": "require_memory"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",node=~\"^$node$\"}) by (node)",
       "legendFormat": "limit_cpu"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",node=~\"^$node$\"}) by (node)",
       "legendFormat": "limit_memory"
      },
      {
       "expr": "sum(label_join(rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}[$interval]), \"node\", \"\", \"instance\")) by (node)"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"^$node$\"}) by (node)"
      },
      {
       "expr": "sum(label_join(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}, \"node\", \"\", \"instance\")) by (node)"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\",node=~\"^$node$\"}) by (node)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage ($interval avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container!=\"\",namespace=~\"^$namespace$\",pod=~\"^$pod$\"}[$interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Containers CPU usage ($interval avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container!=\"\",namespace=~\"^$namespace$\",pod=~\"^$pod$\"}[$interval])) by (pod, container)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",container!=\"\",namespace=~\"^$namespace$\",pod=~\"^$pod$\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Containers memory usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",container!=\"\",namespace=~\"^$namespace$\",pod=~\"^$pod$\"}) by (pod, container)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network IO ($interval avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",namespace=~\"^$namespace$\",pod=~\"^$pod$\"}[$interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Running Warning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Restart Total",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "max(kube_pod_container_status_restarts_total) by (namespace, pod, container) > 0",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Resource Warning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu Utilization Rate > 75%",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (cluster, namespace, pod, container) / sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (cluster, namespace, pod, container) > 0.75",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mem Utilization Rate > 75%",
     "type": "table",
     "description": "This panel shows container memory usage:\n\ncontainer_memory_working_set_bytes / kube_pod_container_resource_limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes) by (cluster, namespace, pod, container)/sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (cluster, namespace, pod, container) > 0.75",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cpu CFS Utilization Rate > 25%",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container!=\"\"}[5m])) by (container, pod, namespace) / sum(increase(container_cpu_cfs_periods_total{}[5m])) by (container, pod, namespace) > ( 25 / 100 )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}