- name: install PIP
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-venv
    - libaugeas0
    - nginx

- name: Configure Nginx
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: Set up a virtual environment
  command: "python3 -m venv /opt/certbot/"

- name: Set up a virtual environment
  command: "/opt/certbot/bin/pip install --upgrade pip"

- name: Install Certbot on NGINX
  command: "/opt/certbot/bin/pip install certbot certbot-nginx"

- name: Create a symlink to ensure Certbot runs
  file:
    src: /opt/certbot/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Create SSL certs for a specified domain
  command: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos -m {{ admin_email }}