- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - tree

- name: Create directory /etc/apt/keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Set permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Add Docker repository to Apt sources
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Docker Engine
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-compose

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes