# - name: Copy the folder
#   copy:
#     src: ./monitoring_vm_files/
#     dest: /home/monitoring/config/

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /home/monitoring/config
    - /home/monitoring/config/docker
    - /home/monitoring/config/grafana
    - /home/monitoring/config/grafana/datasources
    - /home/monitoring/config/grafana/dashboards

- name: Copy docker compose
  template:
    src: docker-compose.yml.j2
    dest: /home/monitoring/config/docker/docker-compose.yml

- name: Copy grafana datasource
  template:
    src: datasources.yaml.j2
    dest: /home/monitoring/config/grafana/datasources/datasources.yaml

- name: Copy grafana dashboards
  template:
    src: dashboards.yaml.j2
    dest: /home/monitoring/config/grafana/dashboards/dashboards.yaml

- name: Copy grafana dashboards for kubernetes
  copy:
    src: grafana-k8s-cluster-dashboard.json
    dest: /home/monitoring/config/grafana/dashboards/grafana-k8s-cluster-dashboard.json

